version: '3.8'
services:
  mongo:
    image: 'mongo:latest'
    container_name: todos-mongodb
    environment:
      - MONGO_INITDB_DATABASE=todos
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init.mongo.js:ro
      - ./mongo-data:/data/db
    ports:
      - 27017-27019:27017-27019
    networks:
      - todos-network

  server-dev:
    image: todos-server
    container_name: todos-server-dev
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    entrypoint: ["yarn", "start:dev"]
    ports: 
      - 3001:3001
      - 3002:9229
    networks:
      - todos-network
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  client-dev:
    image: todos-client
    container_name: todos-client-dev
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    entrypoint: ["yarn", "start"]
    ports: 
      - 3000:3000
    networks:
      - todos-network
    depends_on:
      - mongo
      - server-dev
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  todos-network:
    driver: bridge
